"""Pydantic models for the Apple Search Ads API.

This module exports all the data models used to interact with the
Apple Search Ads API. All models are Pydantic BaseModels with full
type hints and validation.
"""

from asa_api_client.models.acls import UserAcl
from asa_api_client.models.ad_groups import (
    AdGroup,
    AdGroupCreate,
    AdGroupDisplayStatus,
    AdGroupServingStateReason,
    AdGroupServingStatus,
    AdGroupStatus,
    AdGroupUpdate,
    AutomatedKeywordsOptInStatus,
    CpaGoal,
    TargetingDimensions,
)
from asa_api_client.models.ads import (
    Ad,
    AdCreate,
    AdDisplayStatus,
    AdServingStateReason,
    AdServingStatus,
    AdStatus,
    AdUpdate,
    CreativeType,
)
from asa_api_client.models.apps import AppInfo
from asa_api_client.models.base import (
    Condition,
    ConditionOperator,
    Money,
    PageDetail,
    PaginatedResponse,
    Pagination,
    Selector,
    Sorting,
    SortOrder,
)
from asa_api_client.models.budget_orders import BudgetOrder, BudgetOrderStatus
from asa_api_client.models.campaigns import (
    AdChannelType,
    BiddingStrategy,
    BidStrategyType,
    BillingEvent,
    Campaign,
    CampaignCountryOrRegionServingStateReason,
    CampaignCreate,
    CampaignDisplayStatus,
    CampaignServingStateReason,
    CampaignServingStatus,
    CampaignStatus,
    CampaignSupplySource,
    CampaignUpdate,
)
from asa_api_client.models.countries import CountryOrRegion, LanguageDetail
from asa_api_client.models.geo import GeoEntityType, GeoLocation
from asa_api_client.models.keywords import (
    Keyword,
    KeywordCreate,
    KeywordMatchType,
    KeywordStatus,
    KeywordUpdate,
    NegativeKeyword,
    NegativeKeywordCreate,
)
from asa_api_client.models.product_pages import ProductPage, ProductPageLocaleDetail
from asa_api_client.models.reports import (
    GranularityType,
    ImpressionShareDateRange,
    ImpressionShareReport,
    ImpressionShareReportRequest,
    ImpressionShareReportRow,
    ImpressionShareReportStatus,
    MetricData,
    ReportingRequest,
    ReportingResponse,
    ReportMetadata,
    ReportRow,
    SpendRow,
)

__all__ = [
    "Ad",
    "AdChannelType",
    "AdCreate",
    "AdDisplayStatus",
    "AdGroup",
    "AdGroupCreate",
    "AdGroupDisplayStatus",
    "AdGroupServingStateReason",
    "AdGroupServingStatus",
    "AdGroupStatus",
    "AdGroupUpdate",
    "AdServingStateReason",
    "AdServingStatus",
    "AdStatus",
    "AdUpdate",
    "AppInfo",
    "AutomatedKeywordsOptInStatus",
    "BidStrategyType",
    "BiddingStrategy",
    "BillingEvent",
    "BudgetOrder",
    "BudgetOrderStatus",
    "Campaign",
    "CampaignCountryOrRegionServingStateReason",
    "CampaignCreate",
    "CampaignDisplayStatus",
    "CampaignServingStateReason",
    "CampaignServingStatus",
    "CampaignStatus",
    "CampaignSupplySource",
    "CampaignUpdate",
    "Condition",
    "ConditionOperator",
    "CountryOrRegion",
    "CpaGoal",
    "CreativeType",
    "GeoEntityType",
    "GeoLocation",
    "GranularityType",
    "ImpressionShareDateRange",
    "ImpressionShareReport",
    "ImpressionShareReportRequest",
    "ImpressionShareReportRow",
    "ImpressionShareReportStatus",
    "Keyword",
    "KeywordCreate",
    "KeywordMatchType",
    "KeywordStatus",
    "KeywordUpdate",
    "LanguageDetail",
    "MetricData",
    "Money",
    "NegativeKeyword",
    "NegativeKeywordCreate",
    "PageDetail",
    "PaginatedResponse",
    "Pagination",
    "ProductPage",
    "ProductPageLocaleDetail",
    "ReportMetadata",
    "ReportRow",
    "ReportingRequest",
    "ReportingResponse",
    "Selector",
    "SortOrder",
    "Sorting",
    "SpendRow",
    "TargetingDimensions",
    "UserAcl",
]
